[package]
name = "auth"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[features]
mock = ["ed/mock"]
neovim = ["ed/neovim", "keyring/apple-native", "keyring/secret-service"]

[dependencies]
collab-server = { git = "ssh://git@github.com/nomad/collab.git", default-features = false, features = [
  "nomad",
] }
ed = { workspace = true }
event-listener = "5"
keyring = { version = "4.0.0-rc.1", default-features = false }
serde = { workspace = true, features = ["derive"] }
serde_json = "1"

[lints]
workspace = true
