[package]
name = "auth"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[features]
mock = []
neovim = ["keyring/apple-native", "keyring/secret-service", "dep:neovim"]

[dependencies]
abs-path = { workspace = true }
collab-server = { git = "ssh://git@github.com/nomad/collab-server.git", default-features = false, features = [
  "nomad",
] }
ed = { workspace = true }
event-listener = "5"
keyring = { git = "https://git@github.com/open-source-cooperative/keyring-rs.git", branch = "v4", default-features = false }
serde = { workspace = true, features = ["derive"] }
serde_json = "1"

neovim = { workspace = true, optional = true }

[lints]
workspace = true
