[package]
name = "root-finder"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
fs = { workspace = true }
futures-util = { workspace = true }

[lints]
workspace = true
