allow-unwrap-in-tests = true
allowed-duplicate-crates = [
  "getrandom",
  "linux-raw-sys",
  "rand",
  "rand_chacha",
  "rand_core",
  "rustix",
  "thiserror",
  "thiserror-impl",
  "wasi",
  "windows-sys",
  "windows-targets",
  "windows_aarch64_gnullvm",
  "windows_aarch64_msvc",
  "windows_i686_gnu",
  "windows_i686_gnullvm",
  "windows_i686_msvc",
  "windows_x86_64_gnu",
  "windows_x86_64_gnullvm",
  "windows_x86_64_msvc",
]
allowed-wildcard-imports = ["super"]
too-many-arguments-threshold = 4
too-many-lines-threshold = 60
