allow-unwrap-in-tests = true
allowed-duplicate-crates = [
  "getrandom",
  "linux-raw-sys",
  "rand",
  "rand_chacha",
  "rand_core",
  "rustix",
  "thiserror",
  "thiserror-impl",
  "windows-sys",
  "windows-targets",
  "windows_aarch64_gnullvm",
  "windows_aarch64_msvc",
  "windows_i686_gnu",
  "windows_i686_gnullvm",
  "windows_i686_msvc",
  "windows_x86_64_gnu",
  "windows_x86_64_gnullvm",
  "windows_x86_64_msvc",
]
allowed-wildcard-imports = ["super"]
too-many-arguments-threshold = 4
too-many-lines-threshold = 60

# These are only intended for the real-fs package, but clippy doesn't support
# per-package configs yet (see
# https://github.com/rust-lang/rust-clippy/issues/7353 for more infos).
disallowed-methods = [
  { path = "async_fs::File::create", replacement = "crate::File::create" },
  { path = "async_fs::File::open", replacement = "crate::File::new" },
  { path = "async_fs::OpenOptions::open", replacement = "crate::File::new" },
  { path = "async_fs::read_dir", replacement = "crate::Directory::list_metas" },
  { path = "async_fs::read", replacement = "crate::File::read" },
]
