[package]
name = "version"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nvimx2 = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[build-dependencies]
chrono = { version = "0.4", default-features = false }
git2 = { version = "0.20", default-features = false }

[lints]
workspace = true
