[package]
name = "clipboard"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[features]
__ci = []

[dependencies]
copypasta = "0.10"

[lints]
workspace = true
