[package]
name = "tracing-layers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = ["file-appender"]
file-appender = ["dep:tracing-appender", "tracing-subscriber/chrono"]

[dependencies]
abs-path = { workspace = true }
cauchy = { workspace = true }
ed = { workspace = true }
fs = { workspace = true, features = ["os-fs"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

tracing-appender = { workspace = true, optional = true }

[lints]
workspace = true
