[package]
name = "walkdir"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[features]
gitignore = ["ed/os-fs", "dep:compact_str"]

[dependencies]
abs-path = { workspace = true }
cauchy = { workspace = true }
derive_more = { workspace = true }
ed = { workspace = true }
flume = { workspace = true, features = ["async"] }
futures-util = { workspace = true, features = ["default"] }
send-future = "0.1"

compact_str = { workspace = true, optional = true }
either = { workspace = true, optional = true }

[dev-dependencies]
abs-path = { workspace = true, features = ["macros"] }

[lints]
workspace = true
