[package]
name = "walkdir"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = ["gitignore"]
gitignore = ["dep:compact_str", "ed/os-fs"]

# Test-related features.
git-in-PATH = []

[dependencies]
abs-path = { workspace = true }
cauchy = { workspace = true }
derive_more = { workspace = true }
ed = { workspace = true }
flume = { workspace = true, features = ["async"] }
futures-util = { workspace = true, features = ["default"] }
send-future = "0.1"

compact_str = { workspace = true, optional = true }

[dev-dependencies]
abs-path = { workspace = true, features = ["macros"] }
futures-executor = { workspace = true }
mock = { workspace = true }
tempdir = { workspace = true }

[lints]
workspace = true

[[test]]
name = "gitignore"
required-features = ["gitignore"]
