name: "Build and Release"

on:
  workflow_call:
    inputs:
      cachix_auth_token:
        description: "Auth token for pushing Nix artifacts to Cachix"
        required: true
        type: string
      checkout_ref:
        description: "Branch, tag, or commit to checkout and build from"
        required: true
        type: string
      is_stable:
        description: "Whether we're building for a stable release or nightly"
        required: true
        type: boolean
      release_name:
        description: "Name of the release"
        required: true
        type: string
      release_body:
        description: "A markdown-formatted string describing changes in this release"
        required: true
        type: string
      release_tag:
        description: "The tag to attach the release to"
        required: true
        type: string

jobs:
  build-neovim:
    name: build Neovim plugins
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            release-artifacts-package: ".#neovim-release-artifacts-linux"
          - os: macos-latest
            release-artifacts-package: ".#neovim-release-artifacts-macos"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout_ref }}

      - name: Install Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ inputs.cachix_auth_token }}

      - name: Build the Neovim release artifacts
        run: nix build ${{ matrix.release-artifacts-package }}

      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          path: result/*

  release:
    needs: [build-neovim]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          name: ${{ inputs.release_name }}
          body: ${{ inputs.release_body }}
          make_latest: ${{ toString(inputs.is_stable) }}
          prerelease: ${{ !inputs.is_stable }}
          tag_name: ${{ inputs.release_tag }}

      - name: Delete all artifacts after creating the release
        uses: geekyeggo/delete-artifact@v5
        with:
          name: "*"
