[package]
name = "neovim"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[features]
default = ["neovim-0-9"]
neovim-0-9 = ["nvim-oxi/neovim-0-9"]
neovim-nightly = ["nvim-oxi/neovim-nightly"]

[dependencies]
nvim-oxi = { workspace = true, features = ["libuv"] }
pond = { git = "ssh://git@github.com/nomad/pond.git" }

[lints]
workspace = true
