name: "Build and Release"

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: "Branch, tag, or commit to checkout and build from"
        required: true
        type: string
      is-stable:
        description: "Whether we're building for a stable release or nightly"
        required: true
        type: boolean
      release-name:
        description: "Name of the release"
        required: true
        type: string
      release-body:
        description: "A markdown-formatted string describing changes in this release"
        required: true
        type: string
      release-tag:
        description: "The tag to attach the release to"
        required: true
        type: string
    secrets:
      cachix-auth-token:
        description: "Auth token for pushing Nix artifacts to Cachix"
        required: true
      # TODO: remove after publishing private crates.
      ssh-private-keys:
        description: "SSH deploy keys for private repositories"
        required: true

jobs:
  build-neovim:
    name: build Neovim plugins
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            release-artifacts-package: ".#neovim-release-artifacts-linux"
          - os: macos-latest
            release-artifacts-package: ".#neovim-release-artifacts-macos"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Install Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.cachix-auth-token }}
          ssh-private-keys: ${{ secrets.ssh-private-keys }}

      - name: Build the Neovim release artifacts
        run: nix build ${{ matrix.release-artifacts-package }}

      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: neovim-${{ matrix.os }}
          path: result/*

  release:
    needs: [build-neovim]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          name: ${{ inputs.release-name }}
          body: ${{ inputs.release-body }}
          make_latest: ${{ inputs.is-stable && 'true' || 'false' }}
          prerelease: ${{ !inputs.is-stable }}
          tag_name: ${{ inputs.release-tag }}

      - name: Delete all artifacts after creating the release
        uses: geekyeggo/delete-artifact@v5
        with:
          name: "*"
