name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'

# TODO: remove after publishing private crates.
env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  tests:
    name: tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      # TODO: remove after publishing private crates.
      - name: Add the deploy keys of all private repos we depend on
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.ABS_PATH_DEPLOY_KEY }}
            ${{ secrets.CAUCHY_DEPLOY_KEY }}
            ${{ secrets.COLLAB_DEPLOY_KEY }}
            ${{ secrets.LAZY_AWAIT_DEPLOY_KEY }}
            ${{ secrets.PANDO_DEPLOY_KEY }}
            ${{ secrets.PUFF_DEPLOY_KEY }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run tests
        run: nix run .#check-tests --accept-flake-config

  clippy:
    name: clippy
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      # TODO: remove after publishing private crates.
      - name: Add the deploy keys of all private repos we depend on
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.ABS_PATH_DEPLOY_KEY }}
            ${{ secrets.CAUCHY_DEPLOY_KEY }}
            ${{ secrets.COLLAB_DEPLOY_KEY }}
            ${{ secrets.LAZY_AWAIT_DEPLOY_KEY }}
            ${{ secrets.PANDO_DEPLOY_KEY }}
            ${{ secrets.PUFF_DEPLOY_KEY }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run Clippy
        run: nix run .#check-clippy --accept-flake-config

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO: remove after publishing private crates.
      - name: Add the deploy keys of all private repos we depend on
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.ABS_PATH_DEPLOY_KEY }}
            ${{ secrets.CAUCHY_DEPLOY_KEY }}
            ${{ secrets.COLLAB_DEPLOY_KEY }}
            ${{ secrets.LAZY_AWAIT_DEPLOY_KEY }}
            ${{ secrets.PANDO_DEPLOY_KEY }}
            ${{ secrets.PUFF_DEPLOY_KEY }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Generate coverage report
        run: nix build .#coverage --accept-flake-config
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./result/codecov.json
          fail_ci_if_error: true

  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO: remove after publishing private crates.
      - name: Add the deploy keys of all private repos we depend on
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.ABS_PATH_DEPLOY_KEY }}
            ${{ secrets.CAUCHY_DEPLOY_KEY }}
            ${{ secrets.COLLAB_DEPLOY_KEY }}
            ${{ secrets.LAZY_AWAIT_DEPLOY_KEY }}
            ${{ secrets.PANDO_DEPLOY_KEY }}
            ${{ secrets.PUFF_DEPLOY_KEY }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run 'cargo doc'
        run: nix run .#check-docs --accept-flake-config

  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run formatters
        run: nix run .#check-fmt --accept-flake-config

  tests-neovim:
    name: Neovim tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim: [v0.11.2, nightly]
        include:
          - neovim: v0.11.2
            check: "check-tests-neovim"
          - neovim: nightly
            check: "check-tests-neovim-nightly"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      # TODO: remove after publishing private crates.
      - name: Add the deploy keys of all private repos we depend on
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.ABS_PATH_DEPLOY_KEY }}
            ${{ secrets.CAUCHY_DEPLOY_KEY }}
            ${{ secrets.COLLAB_DEPLOY_KEY }}
            ${{ secrets.LAZY_AWAIT_DEPLOY_KEY }}
            ${{ secrets.PANDO_DEPLOY_KEY }}
            ${{ secrets.PUFF_DEPLOY_KEY }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run Neovim tests
        run: nix run .#${{ matrix.check }} --accept-flake-config
