name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test-crates:
    name: test crates/*
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add the deploy keys of all private repos we depend on
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.ABS_PATH_DEPLOY_KEY }}
            ${{ secrets.CAUCHY_DEPLOY_KEY }}
            ${{ secrets.COLLAB_DEPLOY_KEY }}
            ${{ secrets.LAZY_AWAIT_DEPLOY_KEY }}
            ${{ secrets.PANDO_DEPLOY_KEY }}
            ${{ secrets.PUFF_DEPLOY_KEY }}
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: Run unit tests for all crates
        working-directory: ./crates
        run: cargo test --no-fail-fast
      - name: Run crates/auth tests
        working-directory: ./tests
        run: cargo test --features=auth --no-fail-fast
      - name: Run crates/collab tests
        working-directory: ./tests
        run: cargo test --features=collab --no-fail-fast
      - name: Run crates/mock tests
        working-directory: ./tests
        run: cargo test --features=mock --no-fail-fast
      - name: Run crates/walkdir tests
        working-directory: ./tests
        run: cargo test --features=walkdir --no-fail-fast

  test-neovim:
    name: test the Neovim backend
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        neovim: [v0.11.2, nightly]
        include:
          - neovim: v0.11.2
            features: "neovim"
          - neovim: nightly
            features: "neovim-nightly"
    steps:
      - uses: actions/checkout@v4
      - name: Add the deploy keys of all private repos we depend on
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.ABS_PATH_DEPLOY_KEY }}
            ${{ secrets.CAUCHY_DEPLOY_KEY }}
            ${{ secrets.COLLAB_DEPLOY_KEY }}
            ${{ secrets.LAZY_AWAIT_DEPLOY_KEY }}
            ${{ secrets.PANDO_DEPLOY_KEY }}
            ${{ secrets.PUFF_DEPLOY_KEY }}
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: Install Neovim ${{ matrix.neovim }}
        uses: rhysd/action-setup-vim@v1
        with:
            neovim: true
            version: ${{ matrix.neovim }}
      - name: Run Neovim tests
        working-directory: ./tests
        run: cargo test --features=${{ matrix.features }} --no-fail-fast

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set PAT to access private repos
        env:
          PAT: ${{ secrets.NOIB3_PAT }}
        run: |
          git config --global --replace-all "url.https://noib3:$PAT@github.com.insteadOf" ssh://git@github.com
          git config --global --add "url.https://noib3:$PAT@github.com.insteadOf" git@github.com
          git config --global --add "url.https://noib3:$PAT@github.com.insteadOf" https://github.com
      - name: Install Neovim nightly
        uses: rhysd/action-setup-vim@v1
        with:
            neovim: true
            version: nightly
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: CI=true cargo llvm-cov --workspace --codecov --output-path codecov.json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          fail_ci_if_error: true

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add the deploy keys of all private repos we depend on
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.ABS_PATH_DEPLOY_KEY }}
            ${{ secrets.CAUCHY_DEPLOY_KEY }}
            ${{ secrets.COLLAB_DEPLOY_KEY }}
            ${{ secrets.LAZY_AWAIT_DEPLOY_KEY }}
            ${{ secrets.PANDO_DEPLOY_KEY }}
            ${{ secrets.PUFF_DEPLOY_KEY }}
      - name: Install Rust nightly with Clippy
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Run `cargo clippy`
        run: cargo clippy --all-features --all-targets --tests --workspace -- -D warnings

  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add the deploy keys of all private repos we depend on
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.ABS_PATH_DEPLOY_KEY }}
            ${{ secrets.CAUCHY_DEPLOY_KEY }}
            ${{ secrets.COLLAB_DEPLOY_KEY }}
            ${{ secrets.LAZY_AWAIT_DEPLOY_KEY }}
            ${{ secrets.PANDO_DEPLOY_KEY }}
            ${{ secrets.PUFF_DEPLOY_KEY }}
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: Run `cargo doc`
        run: cargo doc --all-features --workspace
        env:
          RUSTFLAGS: "-D warnings"
          RUSTDOCFLAGS: "--cfg docsrs"

  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly with rustfmt
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Run `cargo fmt`
        run: cargo fmt --check
