name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# TODO: remove after publishing private crates.
env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  clippy:
    name: clippy
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust cache
        uses: ./.github/actions/setup-rust-cache
      - name: Enter Clippy environment
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          devshell: ".#ci-clippy"
          ssh-private-keys: |
            ${{ secrets.ABS_PATH_DEPLOY_KEY }}
            ${{ secrets.CAUCHY_DEPLOY_KEY }}
            ${{ secrets.COLLAB_DEPLOY_KEY }}
            ${{ secrets.LAZY_AWAIT_DEPLOY_KEY }}
            ${{ secrets.PANDO_DEPLOY_KEY }}
            ${{ secrets.PUFF_DEPLOY_KEY }}
      - name: Run Clippy
        run: cargo clippy --all-features --all-targets --no-deps --workspace

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust cache
        uses: ./.github/actions/setup-rust-cache
      - name: Enter coverage environment
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          devshell: ".#ci-coverage"
          ssh-private-keys: |
            ${{ secrets.ABS_PATH_DEPLOY_KEY }}
            ${{ secrets.CAUCHY_DEPLOY_KEY }}
            ${{ secrets.COLLAB_DEPLOY_KEY }}
            ${{ secrets.LAZY_AWAIT_DEPLOY_KEY }}
            ${{ secrets.PANDO_DEPLOY_KEY }}
            ${{ secrets.PUFF_DEPLOY_KEY }}
      - name: Generate coverage report
        run: |
          cargo llvm-cov --no-report --workspace
          cargo llvm-cov report --codecov --output-path codecov.json
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./codecov.json
          fail_ci_if_error: true

  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust cache
        uses: ./.github/actions/setup-rust-cache
      - name: Enter docs environment
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          devshell: ".#ci-docs"
          ssh-private-keys: |
            ${{ secrets.ABS_PATH_DEPLOY_KEY }}
            ${{ secrets.CAUCHY_DEPLOY_KEY }}
            ${{ secrets.COLLAB_DEPLOY_KEY }}
            ${{ secrets.LAZY_AWAIT_DEPLOY_KEY }}
            ${{ secrets.PANDO_DEPLOY_KEY }}
            ${{ secrets.PUFF_DEPLOY_KEY }}
      - name: Run Rustdoc
        run: cargo doc --all-features --no-deps --workspace

  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Check formatting
        run: nix run .#check-format

  tests:
    name: tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust cache
        uses: ./.github/actions/setup-rust-cache
      - name: Enter test environment
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          devshell: ".#ci-tests"
          ssh-private-keys: |
            ${{ secrets.ABS_PATH_DEPLOY_KEY }}
            ${{ secrets.CAUCHY_DEPLOY_KEY }}
            ${{ secrets.COLLAB_DEPLOY_KEY }}
            ${{ secrets.LAZY_AWAIT_DEPLOY_KEY }}
            ${{ secrets.PANDO_DEPLOY_KEY }}
            ${{ secrets.PUFF_DEPLOY_KEY }}
      - name: Run unit tests
        run: cargo nextest run --workspace --exclude tests --no-fail-fast
      - name: Run integration tests
        run: cargo nextest run --package=tests --no-fail-fast

  tests-neovim:
    name: tests (Neovim)
    strategy:
      fail-fast: false
      matrix:
        neovim: [stable, nightly]
        os: [ubuntu-latest, macos-latest]
        include:
          - neovim: stable
            devshell: ".#ci-tests-neovim"
            features: "neovim"
          - neovim: nightly
            devshell: ".#ci-tests-neovim-nightly"
            features: "neovim-nightly"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust cache
        uses: ./.github/actions/setup-rust-cache
      - name: Enter Neovim test environment
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          devshell: ${{ matrix.devshell }}
          ssh-private-keys: |
            ${{ secrets.ABS_PATH_DEPLOY_KEY }}
            ${{ secrets.CAUCHY_DEPLOY_KEY }}
            ${{ secrets.COLLAB_DEPLOY_KEY }}
            ${{ secrets.LAZY_AWAIT_DEPLOY_KEY }}
            ${{ secrets.PANDO_DEPLOY_KEY }}
            ${{ secrets.PUFF_DEPLOY_KEY }}
      - name: Run Neovim tests
        run: |
          cargo nextest run \
            --package=tests \
            --features=${{ matrix.features }} \
            --no-fail-fast \
              neovim::
