name: Release Stable

on:
  push:
    tags:
      # On every push of a YYYY.MM.PATCH-formatted tag.
      - "[2-9][0-9][0-9][0-9].0[1-9].[0-9]+"
      - "[2-9][0-9][0-9][0-9].1[0-2].[0-9]+"

jobs:
  release-stable:
    needs: setup
    uses: ./.github/workflows/build-and-release.yaml
    secrets: inherit
    with:
      checkout-ref: ${{ github.ref_name }}
      is-stable: true
      release-name: "Nomad ${{ github.ref_name }}"
      release-body: "TODO"
      release-tag: ${{ github.ref_name }}
