name: Release Stable

on:
  push:
    tags:
      # On every push of a semver-formatted tag (with no pre-release label).
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify that the tag's version matches the workspace's version
        uses: ./.github/actions/verify-tag-version-matches-workspace

      - name: Create new stable release
        uses: ./.github/workflows/reusable/build-and-release.yml
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          checkout_ref: ${{ github.ref_name }}
          is_stable: true
          release_name: "Mad ${{ github.ref_name }}"
          release_body: ""
          release_tag: ${{ github.ref_name }}
