[package]
name = "fuzzy-modal"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
neovim-0-9 = []

[dependencies]
common = { path = "../common" }

serde = { version = "1.0", features = ["derive"] }
tracing = { workspace = true }
